name: huangjui
description: good app for your luck.

publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  http: ^0.13.5
  google_sign_in: ^5.3.3
  flutter_facebook_auth: ^4.3.4+2
  responsive_framework: ^0.1.9
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.0+2
  syncfusion_flutter_datepicker: ^20.2.46


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter         

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/for Mock Up Only/
    - assets/images/zodiac & elements/
    - assets/fonts/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Light.ttf
