name: huangjui
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  syncfusion_flutter_datepicker: ^20.2.46

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/zodiac & elements/
    - assets/fonts/


  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Light.ttf
