name: huangjui
description: good app for your luck.

publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: "^0.7.0"
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_svg: ^1.0.3
  http: ^0.13.5
  sign_in_with_apple: ^4.1.0
  google_sign_in: ^5.3.3
  flutter_facebook_auth: ^4.3.4+2
  responsive_framework: ^0.1.9
  fluttertoast: ^8.0.9
  flutter_otp_text_field: ^1.1.0+2
  syncfusion_flutter_datepicker: ^19.4.38
  page_transition: ^2.0.9
  flutter_datetime_picker: ^1.5.1
  restart_app: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/for Mock Up Only/
    - assets/images/zodiac & elements/
    - assets/fonts/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Light.ttf
